project_id = "cdyycdboudurnhvqlrcb"

[functions.sadad-payment]
verify_jwt = true

[functions.sadad-webhook]
verify_jwt = false

[functions.n8n-response]
verify_jwt = false

[functions.send-to-webhook]
verify_jwt = false
