// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-events.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-events.ts
var list_events_default = defineTool({
  name: "list_events",
  title: "List events",
  description: "List the ticketing events (title, date, location, capacity status), newest first.",
  inputSchema: {
    include_archived: z.boolean().describe("Include archived (past season) events as well."),
    limit: z.number().int().min(1).max(50).describe("How many events to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("events").select("id, title, event_date, end_date, location, is_active, is_archived").order("event_date", { ascending: false }).limit(limit);
    if (!include_archived) query = query.eq("is_archived", false);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    const events = (data ?? []).map((e) => ({
      id: String(e.id),
      title: String(e.title),
      event_date: e.event_date ? String(e.event_date) : null,
      end_date: e.end_date ? String(e.end_date) : null,
      location: e.location ? String(e.location) : null,
      is_active: Boolean(e.is_active),
      is_archived: Boolean(e.is_archived)
    }));
    return {
      content: [
        {
          type: "text",
          text: events.length ? events.map((e) => `${e.title} \u2014 ${e.event_date ?? "?"} (${e.id})`).join("\n") : "No events found."
        }
      ],
      structuredContent: { events }
    };
  }
});

// src/lib/mcp/tools/event-sales-summary.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var event_sales_summary_default = defineTool2({
  name: "event_sales_summary",
  title: "Event sales summary",
  description: "Ticket sales and gate attendance for one event: tickets sold per type, revenue, capacity left and how many holders have been scanned in.",
  inputSchema: {
    event_id: z2.string().uuid().describe("Event id, as returned by list_events. Pass the current event when unsure.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const [eventRes, ticketsRes, ordersRes] = await Promise.all([
      supabase.from("events").select("id, title, event_date").eq("id", event_id).maybeSingle(),
      supabase.from("tickets").select("type, price, available_quantity").eq("event_id", event_id),
      supabase.from("orders").select("id, payment_method").eq("event_id", event_id).eq("payment_status", "confirmed")
    ]);
    if (eventRes.error) throw new ToolError2(eventRes.error.message);
    if (!eventRes.data) throw new ToolError2("Event not found");
    if (ticketsRes.error) throw new ToolError2(ticketsRes.error.message);
    if (ordersRes.error) throw new ToolError2(ordersRes.error.message);
    const orders = ordersRes.data ?? [];
    const orderIds = orders.map((o) => String(o.id));
    const onlineOrderIds = new Set(
      orders.filter((o) => o.payment_method === "sadad").map((o) => String(o.id))
    );
    const holders = [];
    for (let i = 0; i < orderIds.length; i += 200) {
      const { data, error } = await supabase.from("ticket_holders").select("order_id, ticket_type, is_present").in("order_id", orderIds.slice(i, i + 200));
      if (error) throw new ToolError2(error.message);
      for (const h of data ?? []) {
        holders.push({
          order_id: String(h.order_id),
          ticket_type: String(h.ticket_type),
          is_present: h.is_present
        });
      }
    }
    const priceByType = /* @__PURE__ */ new Map();
    const capacityByType = /* @__PURE__ */ new Map();
    for (const t of ticketsRes.data ?? []) {
      priceByType.set(String(t.type), Number(t.price) || 0);
      capacityByType.set(String(t.type), Number(t.available_quantity) || 0);
    }
    const byType = {};
    for (const h of holders) {
      const key = h.ticket_type || "normal";
      byType[key] ??= { sold: 0, scanned: 0 };
      byType[key].sold += 1;
      if (h.is_present) byType[key].scanned += 1;
    }
    const ticket_types = Object.entries(byType).map(([type, v]) => {
      const price = priceByType.get(type) ?? 0;
      const capacity = capacityByType.get(type) ?? 0;
      return {
        type,
        sold: v.sold,
        scanned: v.scanned,
        price,
        revenue: v.sold * price,
        capacity,
        remaining: Math.max(0, capacity - v.sold)
      };
    });
    const summary = {
      event: {
        id: String(eventRes.data.id),
        title: String(eventRes.data.title),
        event_date: eventRes.data.event_date ? String(eventRes.data.event_date) : null
      },
      orders_confirmed: orders.length,
      tickets_sold: holders.length,
      tickets_scanned: holders.filter((h) => h.is_present).length,
      tickets_sold_online: holders.filter((h) => onlineOrderIds.has(h.order_id)).length,
      tickets_sold_at_counter: holders.filter((h) => !onlineOrderIds.has(h.order_id)).length,
      revenue_qar: ticket_types.reduce((s, t) => s + t.revenue, 0),
      ticket_types
    };
    return {
      content: [
        {
          type: "text",
          text: `${summary.event.title}: ${summary.tickets_sold} tickets sold, ${summary.tickets_scanned} scanned in, ${summary.revenue_qar} QAR.`
        }
      ],
      structuredContent: { summary }
    };
  }
});

// src/lib/mcp/tools/find-booking.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var find_booking_default = defineTool3({
  name: "find_booking",
  title: "Find a booking",
  description: "Look up one booking by its reference (for example POS-21-09-2026-UY956SR9R) and return the customer, payment status and every ticket holder with their check-in state.",
  inputSchema: {
    booking_reference: z3.string().trim().min(4).describe("The booking reference to look up.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ booking_reference }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: order, error } = await supabase.from("orders").select(
      "id, booking_reference, quantity, total_amount, payment_method, payment_status, created_at, customers(name, phone, email), events(title, event_date)"
    ).eq("booking_reference", booking_reference.trim()).maybeSingle();
    if (error) throw new ToolError3(error.message);
    if (!order) throw new ToolError3("No booking found with that reference");
    const { data: holderRows, error: holdersError } = await supabase.from("ticket_holders").select("name, phone, nationality, ticket_type, is_present, confirmed_at, confirmed_by_name").eq("order_id", order.id);
    if (holdersError) throw new ToolError3(holdersError.message);
    const customer = order.customers;
    const event = order.events;
    const booking = {
      booking_reference: String(order.booking_reference),
      payment_status: String(order.payment_status ?? ""),
      payment_method: String(order.payment_method ?? ""),
      total_amount: Number(order.total_amount) || 0,
      created_at: order.created_at ? String(order.created_at) : null,
      customer: {
        name: customer?.name ?? null,
        phone: customer?.phone ?? null,
        email: customer?.email ?? null
      },
      event: {
        title: event?.title ?? null,
        event_date: event?.event_date ?? null
      },
      holders: (holderRows ?? []).map((h) => ({
        name: String(h.name),
        phone: String(h.phone),
        nationality: String(h.nationality),
        ticket_type: String(h.ticket_type),
        checked_in: Boolean(h.is_present),
        checked_in_at: h.confirmed_at ? String(h.confirmed_at) : null,
        checked_in_by: h.confirmed_by_name ? String(h.confirmed_by_name) : null
      }))
    };
    return {
      content: [
        {
          type: "text",
          text: `${booking.booking_reference} \u2014 ${booking.customer.name ?? "?"} \u2014 ${booking.holders.length} ticket(s), payment ${booking.payment_status}.`
        }
      ],
      structuredContent: { booking }
    };
  }
});

// src/lib/mcp/tools/search-customers.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var search_customers_default = defineTool4({
  name: "search_customers",
  title: "Search customers",
  description: "Search customers by part of their name, phone number or email address, and see how many bookings each one has.",
  inputSchema: {
    query: z4.string().trim().min(2).describe("Part of a name, phone number or email."),
    limit: z4.number().int().min(1).max(25).describe("How many customers to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const term = query.replace(/[%,]/g, " ").trim();
    const { data, error } = await supabase.from("customers").select("id, name, phone, email, nationality, created_at").or(`name.ilike.%${term}%,phone.ilike.%${term}%,email.ilike.%${term}%`).order("created_at", { ascending: false }).limit(limit);
    if (error) throw new ToolError4(error.message);
    const rows = data ?? [];
    const customers = [];
    for (const c of rows) {
      const { count } = await supabase.from("orders").select("id", { count: "exact", head: true }).eq("customer_id", c.id);
      customers.push({
        id: String(c.id),
        name: String(c.name),
        phone: String(c.phone),
        email: String(c.email),
        nationality: c.nationality ? String(c.nationality) : null,
        bookings: count ?? 0
      });
    }
    return {
      content: [
        {
          type: "text",
          text: customers.length ? customers.map((c) => `${c.name} \u2014 ${c.phone} (${c.bookings} bookings)`).join("\n") : "No matching customers."
        }
      ],
      structuredContent: { customers }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cdyycdboudurnhvqlrcb";
var mcp_default = defineMcp({
  name: "qcamelmc",
  title: "qcamelmc",
  version: "0.1.0",
  instructions: "Read-only tools for the qcamelmc ticketing system. Use `list_events` to find an event id, `event_sales_summary` for sales, revenue and gate attendance of that event, `find_booking` to look up a booking by its reference, and `search_customers` to find a customer by name, phone or email. All data is scoped to the signed-in admin account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_events_default, event_sales_summary_default, find_booking_default, search_customers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
